version: '2'

services:
  
  postgres:
    image: postgres:alpine
  
  rails_template_admin_page:
    build: .
    command: unicorn
    volumes:
      - .:/rails_template_admin_page
    ports:
      - "80:8080"
    depends_on:
      - postgres
    environment:
      - DB_HOST=postgres
      - DB_NAME=rails_template_admin_page
